engines:
  govet:
    enabled: true

exclude_patterns:
- "*js"
- "*html"
- "*css"

ratings:
  paths:
    - "**.go"


version: "2"
checks:
  similar-code:
    enabled: false
  identical-code:
    enabled: false
