language: go

go:
  - 1.7.x

sudo: false

branches:
    only:
        - master


go_import_path: github.com/MyNSB/API

install:
    - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH:$GOPATH/src/github.com/MyNSB/mynsb-api"
    - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"

script: 
    go test ./tests
